# Generated by Django 5.1.6 on 2025-07-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_categories_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
